### ISSUE TITLE
Difference in axn 

### ISSUE THREAD

**Issue by Free-rider** [spedygiorgio/lifecontingencies#4]
Hello, 

first at all, thank you for the package. 

I am testing a whole life annuity in arrears with k  = 12, x = 60 and i = 0.04. I am using my own table that I attach with the lx. 

The result in R is as follows:

 > axn(table, x=60, i = 0.04, k=12, payment = "arrears")
[1] 10.82216

Using an Excel (attached) the result is:

10.8272718556912

I am triying to understand the difference after second decimal.  
[life.xlsx](https://github.com/spedygiorgio/lifecontingencies/files/106932/life.xlsx)

Thanks a lot,

**Comment by spedygiorgio** [comment]
As written in the vignette, the computation of axn using fractional payments are sligthly different from the standard formula found in classical actuarial maths books since they use summation of fractional probabilities

(see the vignette and the code)

 

Da: Free-rider [mailto:notifications@github.com] 
Inviato: mercoledì 27 gennaio 2016 17:21
A: spedygiorgio/lifecontingencies <lifecontingencies@noreply.github.com>
Oggetto: [lifecontingencies] Difference in axn (#4)

 

Hello, 

first at all, thank you for the package 

I am testing a whole life annuity in arrears with k = 12, x = 60 and i = 004 I am using my own table that I attach with the lx 

The result in R is as follows:

axn(table, x=60, i = 004, k=12, payment = "arrears")
[1] 1082216

Using an Excel (attached) the result is:

108272718556912

I am triying to understand the difference after second decimal

lifexlsx <https://githubcom/spedygiorgio/lifecontingencies/files/106932/lifexlsx> 

Thanks a lot,

**Comment by Free-rider** [comment]
Thanks!
