### ISSUE TITLE
missing documentation entries

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/lifecontingencies#9]
When compiling to resubmit the package on CRAN I found this Warning...

* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  'lifetable'
All user-level objects in a package should have documentation entries.

It seems the constructor to have been altered since last commit

**Comment by eschirmacher** [comment]
Hi Giorgio,

I did not write a documentation file for the **lifetable** constructor.  I'll send in a pull request shortly.

But I also wanted to mention another issue I ran across.  When checking the package via the "Check" button in RStudio I got an error message when trying to build the vignette "an_introduction_to_lifecontingencies_package.Rnw"

> Error: processing vignette 'an_introduction_to_lifecontingencies_package.Rnw' failed with diagnostics:
>  chunk 5 (label = structure3) 
> Error : evaluation nested too deeply: infinite recursion / options(expressions=)?
> Execution halted

This error occurs when you try to evaluate the following function in **R**:
`showMethods(classes=c("actuarialtable","lifetable"))`

Take a look and see if you get a similar error.

Thanks,

Ernesto

**Comment by spedygiorgio** [comment]
Hi Ernesto, I did not find that error (but I compiled the package on 3.2.2.). What it seems strange to me is that TRAVIS CI seems all ok. What I can do is to compare the CRAN published and the committed version of lifecontingencies class... I think it is a weird issues.

**Comment by spedygiorgio** [comment]
I probably found the error... There was need to write an initialize method for both lifetable and actuarialtable classes

**Comment by eschirmacher** [comment]
Since I wrote an initialize method for lifetable I also was supposed to write the user documentation for it. That is the real issue.  I have not written an initialize method for actuarialtable.  Once I do that I'll also write the accompanying documentation file.

I was also working with with a couple of other branches on my local git repository and since I'm fairly new at git I got myself confused with the branches and commits.

I have re-initialized my fork of lifecontingencies and later today I'll submit a pull request for the documentation of lifetable.

Would you mind closing the current pull request?

thank you very much!

**Comment by spedygiorgio** [comment]
the issue is closed, I also sligthy modified the test (making lifetables to be created by new("lifetable"))

**Comment by eschirmacher** [comment]
Ok.  Since you have lifetables created by **new** then there is no need for a lifetable function that constructs the object (all taken care within the initialize method).

There is some duplication of code for the initialize method for new lifetable and new actuarialtable.
